spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#mybatisPlus
mybatis-plus:
  type-aliases-package: com.soplong.domain
  configuration:
#    这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    驼峰下划线转换
    map-underscore-to-camel-case: true
#    配置的缓存的全局开关
    cache-enabled: false
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  mapper-locations: classpath:/mapper/*/*Mapper.xml
server:
  port: 8800